
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABD/AAAA8PDw8PDw8PDw8PDwdXEAfgACAAAAC/Dw8PDw8PDw8PAAeA==");
