
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABCC6wAAAAAAAAAAAOvr6+vrdXEAfgACAAAAC+vr6+vr6+vr6+vreA==");
