
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABD/jo6Ojo6Ojo6Ojo6Ojo6OdXEAfgACAAAADY6Ojo6Ojo6Ojo6OjoR4");
