
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABDNzc3Nzc3Nzc3Nzc3Nzc3NdXEAfgACAAAADc3Nzc3Nzc3Nzc0aez94");
