
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABDl5eXl5eXl5eXl5eXl5eXldXEAfgACAAAADeXl5eXl5eXcAAAG9Sp4");
