
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABD/AAAAAAAAAAAAAf//3/9cdXEAfgACAAAADv8AAAAAAAAAAAAA//0ueA==");
