
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABA6Ojo6Ojo6Ojo6Ojo6Ojo6dXEAfgACAAAADDo6Ojo6Ojo6Ojr/P3g=");
