
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABAATk5OTk5OTk5OAAZOTk5OdXEAfgACAAAAC05OTk5OTk5OTk4AeA==");
