
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABCZCh4eHh4eHh4eHh4eHh4edXEAfgACAAAADR4eHh4eHh4eHh4eHpl4");
