
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABDCwsLCwsLCwsLCwsLCwsLCdXEAfgACAAAADMLCwsLCwsLCwgD/+3g=");
