
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABD/w8PDw8PDw8PDw8PDw8PDdXEAfgACAAAAC8PDw8PDw8PDw8PDeA==");
