
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABDWlnoeHh4eHh4e3R4eHh4edXEAfgACAAAADB4eHh4eHh4eHh4fHng=");
