
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABAaCtFLS0tLSxgAAABLJEsmdXEAfgACAAAADUtLS0tLS0tLS0tLS0t4");
