
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABAvLy8vLy8vLy8vLy8vLy8vdXEAfgACAAAACy8vLy8vLy8vLy+veA==");
