
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAACdwQAAAACdXIAAltCrPMX+AYIVOACAAB4cAAAABD2AAAAAAAAAAAAAAAAAAAAdXEAfgACAAAADw8PDw8PHwAAAAAAAADxPXg=");
